version: '2'
services:
    cmsproject-app:
        image: cmsproject
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://cmsproject-postgresql:5432/cmsproject
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=cmsproject-elasticsearch:9300
        ports:
            - 8080:8080
    cmsproject-postgresql:
        extends:
            file: postgresql.yml
            service: cmsproject-postgresql
    cmsproject-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: cmsproject-elasticsearch
